/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppSavedRouteImport } from './routes/_app/_saved'
import { Route as AppProfileRouteImport } from './routes/_app/$profile'
import { Route as AppSavedVaultRouteImport } from './routes/_app/_saved/vault'
import { Route as AppSavedSendRouteImport } from './routes/_app/_saved/send'
import { Route as AppSavedPasswordRouteImport } from './routes/_app/_saved/password'
import { Route as AppSavedKeysRouteImport } from './routes/_app/_saved/keys'
import { Route as AppSavedInboxRouteImport } from './routes/_app/_saved/inbox'
import { Route as AppSavedChannelIdRouteImport } from './routes/_app/_saved/channel.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/_saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/$profile',
  path: '/$profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedVaultRoute = AppSavedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedSendRoute = AppSavedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedPasswordRoute = AppSavedPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedKeysRoute = AppSavedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedInboxRoute = AppSavedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedChannelIdRoute = AppSavedChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => AppSavedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$profile': typeof AppProfileRoute
  '/welcome': typeof AppWelcomeRoute
  '/inbox': typeof AppSavedInboxRoute
  '/keys': typeof AppSavedKeysRoute
  '/password': typeof AppSavedPasswordRoute
  '/send': typeof AppSavedSendRoute
  '/vault': typeof AppSavedVaultRoute
  '/channel/$id': typeof AppSavedChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$profile': typeof AppProfileRoute
  '/welcome': typeof AppWelcomeRoute
  '/inbox': typeof AppSavedInboxRoute
  '/keys': typeof AppSavedKeysRoute
  '/password': typeof AppSavedPasswordRoute
  '/send': typeof AppSavedSendRoute
  '/vault': typeof AppSavedVaultRoute
  '/channel/$id': typeof AppSavedChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$profile': typeof AppProfileRoute
  '/_app/_saved': typeof AppSavedRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/_saved/inbox': typeof AppSavedInboxRoute
  '/_app/_saved/keys': typeof AppSavedKeysRoute
  '/_app/_saved/password': typeof AppSavedPasswordRoute
  '/_app/_saved/send': typeof AppSavedSendRoute
  '/_app/_saved/vault': typeof AppSavedVaultRoute
  '/_app/_saved/channel/$id': typeof AppSavedChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$profile'
    | '/welcome'
    | '/inbox'
    | '/keys'
    | '/password'
    | '/send'
    | '/vault'
    | '/channel/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$profile'
    | '/welcome'
    | '/inbox'
    | '/keys'
    | '/password'
    | '/send'
    | '/vault'
    | '/channel/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$profile'
    | '/_app/_saved'
    | '/_app/welcome'
    | '/_app/_saved/inbox'
    | '/_app/_saved/keys'
    | '/_app/_saved/password'
    | '/_app/_saved/send'
    | '/_app/_saved/vault'
    | '/_app/_saved/channel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_saved': {
      id: '/_app/_saved'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$profile': {
      id: '/_app/$profile'
      path: '/$profile'
      fullPath: '/$profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_saved/vault': {
      id: '/_app/_saved/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppSavedVaultRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/send': {
      id: '/_app/_saved/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSavedSendRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/password': {
      id: '/_app/_saved/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AppSavedPasswordRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/keys': {
      id: '/_app/_saved/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppSavedKeysRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/inbox': {
      id: '/_app/_saved/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppSavedInboxRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/channel/$id': {
      id: '/_app/_saved/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof AppSavedChannelIdRouteImport
      parentRoute: typeof AppSavedRoute
    }
  }
}

interface AppSavedRouteChildren {
  AppSavedInboxRoute: typeof AppSavedInboxRoute
  AppSavedKeysRoute: typeof AppSavedKeysRoute
  AppSavedPasswordRoute: typeof AppSavedPasswordRoute
  AppSavedSendRoute: typeof AppSavedSendRoute
  AppSavedVaultRoute: typeof AppSavedVaultRoute
  AppSavedChannelIdRoute: typeof AppSavedChannelIdRoute
}

const AppSavedRouteChildren: AppSavedRouteChildren = {
  AppSavedInboxRoute: AppSavedInboxRoute,
  AppSavedKeysRoute: AppSavedKeysRoute,
  AppSavedPasswordRoute: AppSavedPasswordRoute,
  AppSavedSendRoute: AppSavedSendRoute,
  AppSavedVaultRoute: AppSavedVaultRoute,
  AppSavedChannelIdRoute: AppSavedChannelIdRoute,
}

const AppSavedRouteWithChildren = AppSavedRoute._addFileChildren(
  AppSavedRouteChildren,
)

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
