/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsDocsRouteImport } from './routes/_docs/docs'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppSavedRouteImport } from './routes/_app/_saved'
import { Route as DocsDocsSelfHostingRouteImport } from './routes/_docs/docs.self-hosting'
import { Route as DocsDocsSecurityRouteImport } from './routes/_docs/docs.security'
import { Route as DocsDocsFederationRouteImport } from './routes/_docs/docs.federation'
import { Route as DocsDocsDevelopmentRouteImport } from './routes/_docs/docs.development'
import { Route as AppSavedChromeRouteImport } from './routes/_app/_saved/_chrome'
import { Route as DocsDocsProtocolProofOfWorkRouteImport } from './routes/_docs/docs.protocol.proof-of-work'
import { Route as DocsDocsProtocolKeyDerivationRouteImport } from './routes/_docs/docs.protocol.key-derivation'
import { Route as DocsDocsProtocolEncryptionRouteImport } from './routes/_docs/docs.protocol.encryption'
import { Route as DocsDocsProtocolAddressingRouteImport } from './routes/_docs/docs.protocol.addressing'
import { Route as AppSavedVaultIdRouteImport } from './routes/_app/_saved/vault.$id'
import { Route as AppSavedChannelAddressRouteImport } from './routes/_app/_saved/channel.$address'
import { Route as AppSavedChromeVaultRouteImport } from './routes/_app/_saved/_chrome/vault'
import { Route as AppSavedChromeSettingsRouteImport } from './routes/_app/_saved/_chrome/settings'
import { Route as AppSavedChromeSendRouteImport } from './routes/_app/_saved/_chrome/send'
import { Route as AppSavedChromePasswordRouteImport } from './routes/_app/_saved/_chrome/password'
import { Route as AppSavedChromeKeysRouteImport } from './routes/_app/_saved/_chrome/keys'
import { Route as AppSavedChromeInboxRouteImport } from './routes/_app/_saved/_chrome/inbox'
import { Route as AppSavedChromeHomeRouteImport } from './routes/_app/_saved/_chrome/home'
import { Route as AppSavedChromeDomainsRouteImport } from './routes/_app/_saved/_chrome/domains'
import { Route as AppSavedChromeProfileRouteImport } from './routes/_app/_saved/_chrome/$profile'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsRoute = DocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocsRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/_saved',
  getParentRoute: () => AppRoute,
} as any)
const DocsDocsSelfHostingRoute = DocsDocsSelfHostingRouteImport.update({
  id: '/self-hosting',
  path: '/self-hosting',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsSecurityRoute = DocsDocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsFederationRoute = DocsDocsFederationRouteImport.update({
  id: '/federation',
  path: '/federation',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsDevelopmentRoute = DocsDocsDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => DocsDocsRoute,
} as any)
const AppSavedChromeRoute = AppSavedChromeRouteImport.update({
  id: '/_chrome',
  getParentRoute: () => AppSavedRoute,
} as any)
const DocsDocsProtocolProofOfWorkRoute =
  DocsDocsProtocolProofOfWorkRouteImport.update({
    id: '/protocol/proof-of-work',
    path: '/protocol/proof-of-work',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsProtocolKeyDerivationRoute =
  DocsDocsProtocolKeyDerivationRouteImport.update({
    id: '/protocol/key-derivation',
    path: '/protocol/key-derivation',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsProtocolEncryptionRoute =
  DocsDocsProtocolEncryptionRouteImport.update({
    id: '/protocol/encryption',
    path: '/protocol/encryption',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsProtocolAddressingRoute =
  DocsDocsProtocolAddressingRouteImport.update({
    id: '/protocol/addressing',
    path: '/protocol/addressing',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const AppSavedVaultIdRoute = AppSavedVaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedChannelAddressRoute = AppSavedChannelAddressRouteImport.update({
  id: '/channel/$address',
  path: '/channel/$address',
  getParentRoute: () => AppSavedRoute,
} as any)
const AppSavedChromeVaultRoute = AppSavedChromeVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeSettingsRoute = AppSavedChromeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeSendRoute = AppSavedChromeSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromePasswordRoute = AppSavedChromePasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeKeysRoute = AppSavedChromeKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeInboxRoute = AppSavedChromeInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeHomeRoute = AppSavedChromeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeDomainsRoute = AppSavedChromeDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppSavedChromeRoute,
} as any)
const AppSavedChromeProfileRoute = AppSavedChromeProfileRouteImport.update({
  id: '/$profile',
  path: '/$profile',
  getParentRoute: () => AppSavedChromeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof AppWelcomeRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/development': typeof DocsDocsDevelopmentRoute
  '/docs/federation': typeof DocsDocsFederationRoute
  '/docs/security': typeof DocsDocsSecurityRoute
  '/docs/self-hosting': typeof DocsDocsSelfHostingRoute
  '/$profile': typeof AppSavedChromeProfileRoute
  '/domains': typeof AppSavedChromeDomainsRoute
  '/home': typeof AppSavedChromeHomeRoute
  '/inbox': typeof AppSavedChromeInboxRoute
  '/keys': typeof AppSavedChromeKeysRoute
  '/password': typeof AppSavedChromePasswordRoute
  '/send': typeof AppSavedChromeSendRoute
  '/settings': typeof AppSavedChromeSettingsRoute
  '/vault': typeof AppSavedChromeVaultRoute
  '/channel/$address': typeof AppSavedChannelAddressRoute
  '/vault/$id': typeof AppSavedVaultIdRoute
  '/docs/protocol/addressing': typeof DocsDocsProtocolAddressingRoute
  '/docs/protocol/encryption': typeof DocsDocsProtocolEncryptionRoute
  '/docs/protocol/key-derivation': typeof DocsDocsProtocolKeyDerivationRoute
  '/docs/protocol/proof-of-work': typeof DocsDocsProtocolProofOfWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof AppWelcomeRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/development': typeof DocsDocsDevelopmentRoute
  '/docs/federation': typeof DocsDocsFederationRoute
  '/docs/security': typeof DocsDocsSecurityRoute
  '/docs/self-hosting': typeof DocsDocsSelfHostingRoute
  '/$profile': typeof AppSavedChromeProfileRoute
  '/domains': typeof AppSavedChromeDomainsRoute
  '/home': typeof AppSavedChromeHomeRoute
  '/inbox': typeof AppSavedChromeInboxRoute
  '/keys': typeof AppSavedChromeKeysRoute
  '/password': typeof AppSavedChromePasswordRoute
  '/send': typeof AppSavedChromeSendRoute
  '/settings': typeof AppSavedChromeSettingsRoute
  '/vault': typeof AppSavedChromeVaultRoute
  '/channel/$address': typeof AppSavedChannelAddressRoute
  '/vault/$id': typeof AppSavedVaultIdRoute
  '/docs/protocol/addressing': typeof DocsDocsProtocolAddressingRoute
  '/docs/protocol/encryption': typeof DocsDocsProtocolEncryptionRoute
  '/docs/protocol/key-derivation': typeof DocsDocsProtocolKeyDerivationRoute
  '/docs/protocol/proof-of-work': typeof DocsDocsProtocolProofOfWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/_saved': typeof AppSavedRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/_docs/docs': typeof DocsDocsRouteWithChildren
  '/_app/_saved/_chrome': typeof AppSavedChromeRouteWithChildren
  '/_docs/docs/development': typeof DocsDocsDevelopmentRoute
  '/_docs/docs/federation': typeof DocsDocsFederationRoute
  '/_docs/docs/security': typeof DocsDocsSecurityRoute
  '/_docs/docs/self-hosting': typeof DocsDocsSelfHostingRoute
  '/_app/_saved/_chrome/$profile': typeof AppSavedChromeProfileRoute
  '/_app/_saved/_chrome/domains': typeof AppSavedChromeDomainsRoute
  '/_app/_saved/_chrome/home': typeof AppSavedChromeHomeRoute
  '/_app/_saved/_chrome/inbox': typeof AppSavedChromeInboxRoute
  '/_app/_saved/_chrome/keys': typeof AppSavedChromeKeysRoute
  '/_app/_saved/_chrome/password': typeof AppSavedChromePasswordRoute
  '/_app/_saved/_chrome/send': typeof AppSavedChromeSendRoute
  '/_app/_saved/_chrome/settings': typeof AppSavedChromeSettingsRoute
  '/_app/_saved/_chrome/vault': typeof AppSavedChromeVaultRoute
  '/_app/_saved/channel/$address': typeof AppSavedChannelAddressRoute
  '/_app/_saved/vault/$id': typeof AppSavedVaultIdRoute
  '/_docs/docs/protocol/addressing': typeof DocsDocsProtocolAddressingRoute
  '/_docs/docs/protocol/encryption': typeof DocsDocsProtocolEncryptionRoute
  '/_docs/docs/protocol/key-derivation': typeof DocsDocsProtocolKeyDerivationRoute
  '/_docs/docs/protocol/proof-of-work': typeof DocsDocsProtocolProofOfWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/welcome'
    | '/docs'
    | '/docs/development'
    | '/docs/federation'
    | '/docs/security'
    | '/docs/self-hosting'
    | '/$profile'
    | '/domains'
    | '/home'
    | '/inbox'
    | '/keys'
    | '/password'
    | '/send'
    | '/settings'
    | '/vault'
    | '/channel/$address'
    | '/vault/$id'
    | '/docs/protocol/addressing'
    | '/docs/protocol/encryption'
    | '/docs/protocol/key-derivation'
    | '/docs/protocol/proof-of-work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/welcome'
    | '/docs'
    | '/docs/development'
    | '/docs/federation'
    | '/docs/security'
    | '/docs/self-hosting'
    | '/$profile'
    | '/domains'
    | '/home'
    | '/inbox'
    | '/keys'
    | '/password'
    | '/send'
    | '/settings'
    | '/vault'
    | '/channel/$address'
    | '/vault/$id'
    | '/docs/protocol/addressing'
    | '/docs/protocol/encryption'
    | '/docs/protocol/key-derivation'
    | '/docs/protocol/proof-of-work'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/_saved'
    | '/_app/welcome'
    | '/_docs/docs'
    | '/_app/_saved/_chrome'
    | '/_docs/docs/development'
    | '/_docs/docs/federation'
    | '/_docs/docs/security'
    | '/_docs/docs/self-hosting'
    | '/_app/_saved/_chrome/$profile'
    | '/_app/_saved/_chrome/domains'
    | '/_app/_saved/_chrome/home'
    | '/_app/_saved/_chrome/inbox'
    | '/_app/_saved/_chrome/keys'
    | '/_app/_saved/_chrome/password'
    | '/_app/_saved/_chrome/send'
    | '/_app/_saved/_chrome/settings'
    | '/_app/_saved/_chrome/vault'
    | '/_app/_saved/channel/$address'
    | '/_app/_saved/vault/$id'
    | '/_docs/docs/protocol/addressing'
    | '/_docs/docs/protocol/encryption'
    | '/_docs/docs/protocol/key-derivation'
    | '/_docs/docs/protocol/proof-of-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs': {
      id: '/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_saved': {
      id: '/_app/_saved'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_docs/docs/self-hosting': {
      id: '/_docs/docs/self-hosting'
      path: '/self-hosting'
      fullPath: '/docs/self-hosting'
      preLoaderRoute: typeof DocsDocsSelfHostingRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/security': {
      id: '/_docs/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsDocsSecurityRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/federation': {
      id: '/_docs/docs/federation'
      path: '/federation'
      fullPath: '/docs/federation'
      preLoaderRoute: typeof DocsDocsFederationRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/development': {
      id: '/_docs/docs/development'
      path: '/development'
      fullPath: '/docs/development'
      preLoaderRoute: typeof DocsDocsDevelopmentRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_app/_saved/_chrome': {
      id: '/_app/_saved/_chrome'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSavedChromeRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_docs/docs/protocol/proof-of-work': {
      id: '/_docs/docs/protocol/proof-of-work'
      path: '/protocol/proof-of-work'
      fullPath: '/docs/protocol/proof-of-work'
      preLoaderRoute: typeof DocsDocsProtocolProofOfWorkRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/protocol/key-derivation': {
      id: '/_docs/docs/protocol/key-derivation'
      path: '/protocol/key-derivation'
      fullPath: '/docs/protocol/key-derivation'
      preLoaderRoute: typeof DocsDocsProtocolKeyDerivationRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/protocol/encryption': {
      id: '/_docs/docs/protocol/encryption'
      path: '/protocol/encryption'
      fullPath: '/docs/protocol/encryption'
      preLoaderRoute: typeof DocsDocsProtocolEncryptionRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/protocol/addressing': {
      id: '/_docs/docs/protocol/addressing'
      path: '/protocol/addressing'
      fullPath: '/docs/protocol/addressing'
      preLoaderRoute: typeof DocsDocsProtocolAddressingRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_app/_saved/vault/$id': {
      id: '/_app/_saved/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof AppSavedVaultIdRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/channel/$address': {
      id: '/_app/_saved/channel/$address'
      path: '/channel/$address'
      fullPath: '/channel/$address'
      preLoaderRoute: typeof AppSavedChannelAddressRouteImport
      parentRoute: typeof AppSavedRoute
    }
    '/_app/_saved/_chrome/vault': {
      id: '/_app/_saved/_chrome/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppSavedChromeVaultRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/settings': {
      id: '/_app/_saved/_chrome/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSavedChromeSettingsRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/send': {
      id: '/_app/_saved/_chrome/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSavedChromeSendRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/password': {
      id: '/_app/_saved/_chrome/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AppSavedChromePasswordRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/keys': {
      id: '/_app/_saved/_chrome/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppSavedChromeKeysRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/inbox': {
      id: '/_app/_saved/_chrome/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppSavedChromeInboxRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/home': {
      id: '/_app/_saved/_chrome/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppSavedChromeHomeRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/domains': {
      id: '/_app/_saved/_chrome/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppSavedChromeDomainsRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
    '/_app/_saved/_chrome/$profile': {
      id: '/_app/_saved/_chrome/$profile'
      path: '/$profile'
      fullPath: '/$profile'
      preLoaderRoute: typeof AppSavedChromeProfileRouteImport
      parentRoute: typeof AppSavedChromeRoute
    }
  }
}

interface AppSavedChromeRouteChildren {
  AppSavedChromeProfileRoute: typeof AppSavedChromeProfileRoute
  AppSavedChromeDomainsRoute: typeof AppSavedChromeDomainsRoute
  AppSavedChromeHomeRoute: typeof AppSavedChromeHomeRoute
  AppSavedChromeInboxRoute: typeof AppSavedChromeInboxRoute
  AppSavedChromeKeysRoute: typeof AppSavedChromeKeysRoute
  AppSavedChromePasswordRoute: typeof AppSavedChromePasswordRoute
  AppSavedChromeSendRoute: typeof AppSavedChromeSendRoute
  AppSavedChromeSettingsRoute: typeof AppSavedChromeSettingsRoute
  AppSavedChromeVaultRoute: typeof AppSavedChromeVaultRoute
}

const AppSavedChromeRouteChildren: AppSavedChromeRouteChildren = {
  AppSavedChromeProfileRoute: AppSavedChromeProfileRoute,
  AppSavedChromeDomainsRoute: AppSavedChromeDomainsRoute,
  AppSavedChromeHomeRoute: AppSavedChromeHomeRoute,
  AppSavedChromeInboxRoute: AppSavedChromeInboxRoute,
  AppSavedChromeKeysRoute: AppSavedChromeKeysRoute,
  AppSavedChromePasswordRoute: AppSavedChromePasswordRoute,
  AppSavedChromeSendRoute: AppSavedChromeSendRoute,
  AppSavedChromeSettingsRoute: AppSavedChromeSettingsRoute,
  AppSavedChromeVaultRoute: AppSavedChromeVaultRoute,
}

const AppSavedChromeRouteWithChildren = AppSavedChromeRoute._addFileChildren(
  AppSavedChromeRouteChildren,
)

interface AppSavedRouteChildren {
  AppSavedChromeRoute: typeof AppSavedChromeRouteWithChildren
  AppSavedChannelAddressRoute: typeof AppSavedChannelAddressRoute
  AppSavedVaultIdRoute: typeof AppSavedVaultIdRoute
}

const AppSavedRouteChildren: AppSavedRouteChildren = {
  AppSavedChromeRoute: AppSavedChromeRouteWithChildren,
  AppSavedChannelAddressRoute: AppSavedChannelAddressRoute,
  AppSavedVaultIdRoute: AppSavedVaultIdRoute,
}

const AppSavedRouteWithChildren = AppSavedRoute._addFileChildren(
  AppSavedRouteChildren,
)

interface AppRouteChildren {
  AppSavedRoute: typeof AppSavedRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSavedRoute: AppSavedRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsDocsRouteChildren {
  DocsDocsDevelopmentRoute: typeof DocsDocsDevelopmentRoute
  DocsDocsFederationRoute: typeof DocsDocsFederationRoute
  DocsDocsSecurityRoute: typeof DocsDocsSecurityRoute
  DocsDocsSelfHostingRoute: typeof DocsDocsSelfHostingRoute
  DocsDocsProtocolAddressingRoute: typeof DocsDocsProtocolAddressingRoute
  DocsDocsProtocolEncryptionRoute: typeof DocsDocsProtocolEncryptionRoute
  DocsDocsProtocolKeyDerivationRoute: typeof DocsDocsProtocolKeyDerivationRoute
  DocsDocsProtocolProofOfWorkRoute: typeof DocsDocsProtocolProofOfWorkRoute
}

const DocsDocsRouteChildren: DocsDocsRouteChildren = {
  DocsDocsDevelopmentRoute: DocsDocsDevelopmentRoute,
  DocsDocsFederationRoute: DocsDocsFederationRoute,
  DocsDocsSecurityRoute: DocsDocsSecurityRoute,
  DocsDocsSelfHostingRoute: DocsDocsSelfHostingRoute,
  DocsDocsProtocolAddressingRoute: DocsDocsProtocolAddressingRoute,
  DocsDocsProtocolEncryptionRoute: DocsDocsProtocolEncryptionRoute,
  DocsDocsProtocolKeyDerivationRoute: DocsDocsProtocolKeyDerivationRoute,
  DocsDocsProtocolProofOfWorkRoute: DocsDocsProtocolProofOfWorkRoute,
}

const DocsDocsRouteWithChildren = DocsDocsRoute._addFileChildren(
  DocsDocsRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsRoute: typeof DocsDocsRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsRoute: DocsDocsRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
