export type AIcon =
  "/images/black-button-128.ico" |
  "/images/black-button-128.webp" |
  "/images/black-button-180.webp" |
  "/images/black-button-200.webp" |
  "/images/black-button-300.webp" |
  "/images/black-button-32.webp" |
  "/images/black-button-400.webp" |
  "/images/black-button-64.webp" |
  "/images/black-button-96.webp" |
  "/images/blue-at-symbol-128.ico" |
  "/images/blue-at-symbol-128.webp" |
  "/images/blue-at-symbol-180.webp" |
  "/images/blue-at-symbol-200.webp" |
  "/images/blue-at-symbol-300.webp" |
  "/images/blue-at-symbol-32.webp" |
  "/images/blue-at-symbol-400.webp" |
  "/images/blue-at-symbol-64.webp" |
  "/images/blue-at-symbol-96.webp" |
  "/images/checkmark-envelope-128.ico" |
  "/images/checkmark-envelope-128.webp" |
  "/images/checkmark-envelope-180.webp" |
  "/images/checkmark-envelope-200.webp" |
  "/images/checkmark-envelope-300.webp" |
  "/images/checkmark-envelope-32.webp" |
  "/images/checkmark-envelope-400.webp" |
  "/images/checkmark-envelope-64.webp" |
  "/images/checkmark-envelope-96.webp" |
  "/images/earthbucks-128.ico" |
  "/images/earthbucks-128.webp" |
  "/images/earthbucks-180.webp" |
  "/images/earthbucks-200.webp" |
  "/images/earthbucks-300.webp" |
  "/images/earthbucks-32.webp" |
  "/images/earthbucks-400.webp" |
  "/images/earthbucks-64.webp" |
  "/images/earthbucks-96.webp" |
  "/images/fruitcake-128.ico" |
  "/images/fruitcake-128.webp" |
  "/images/fruitcake-180.webp" |
  "/images/fruitcake-200.webp" |
  "/images/fruitcake-300.webp" |
  "/images/fruitcake-32.webp" |
  "/images/fruitcake-400.webp" |
  "/images/fruitcake-64.webp" |
  "/images/fruitcake-96.webp" |
  "/images/identellica-128.ico" |
  "/images/identellica-128.webp" |
  "/images/identellica-180.webp" |
  "/images/identellica-200.webp" |
  "/images/identellica-300.webp" |
  "/images/identellica-32.webp" |
  "/images/identellica-400.webp" |
  "/images/identellica-64.webp" |
  "/images/identellica-96.webp" |
  "/images/imp-avatar-bw-128.ico" |
  "/images/imp-avatar-bw-128.webp" |
  "/images/imp-avatar-bw-180.webp" |
  "/images/imp-avatar-bw-200.webp" |
  "/images/imp-avatar-bw-300.webp" |
  "/images/imp-avatar-bw-32.webp" |
  "/images/imp-avatar-bw-400.webp" |
  "/images/imp-avatar-bw-64.webp" |
  "/images/imp-avatar-bw-96.webp" |
  "/images/impstack-coin-128.ico" |
  "/images/impstack-coin-128.webp" |
  "/images/impstack-coin-180.webp" |
  "/images/impstack-coin-200.webp" |
  "/images/impstack-coin-300.webp" |
  "/images/impstack-coin-32.webp" |
  "/images/impstack-coin-400.webp" |
  "/images/impstack-coin-64.webp" |
  "/images/impstack-coin-96.webp" |
  "/images/internetkyc-128.ico" |
  "/images/internetkyc-128.webp" |
  "/images/internetkyc-180.webp" |
  "/images/internetkyc-200.webp" |
  "/images/internetkyc-300.webp" |
  "/images/internetkyc-32.webp" |
  "/images/internetkyc-400.webp" |
  "/images/internetkyc-64.webp" |
  "/images/internetkyc-96.webp" |
  "/images/key-128.ico" |
  "/images/key-128.webp" |
  "/images/key-180.webp" |
  "/images/key-200.webp" |
  "/images/key-300.webp" |
  "/images/key-32.webp" |
  "/images/key-400.webp" |
  "/images/key-64.webp" |
  "/images/key-96.webp" |
  "/images/moon-face-128.ico" |
  "/images/moon-face-128.webp" |
  "/images/moon-face-180.webp" |
  "/images/moon-face-200.webp" |
  "/images/moon-face-300.webp" |
  "/images/moon-face-32.webp" |
  "/images/moon-face-400.webp" |
  "/images/moon-face-64.webp" |
  "/images/moon-face-96.webp" |
  "/images/rewind-button-128.ico" |
  "/images/rewind-button-128.webp" |
  "/images/rewind-button-180.webp" |
  "/images/rewind-button-200.webp" |
  "/images/rewind-button-300.webp" |
  "/images/rewind-button-32.webp" |
  "/images/rewind-button-400.webp" |
  "/images/rewind-button-64.webp" |
  "/images/rewind-button-96.webp" |
  "/images/sun-128.ico" |
  "/images/sun-128.webp" |
  "/images/sun-180.webp" |
  "/images/sun-200.webp" |
  "/images/sun-300.webp" |
  "/images/sun-32.webp" |
  "/images/sun-400.webp" |
  "/images/sun-64.webp" |
  "/images/sun-96.webp" |
  "/images/tech-pen-128.ico" |
  "/images/tech-pen-128.webp" |
  "/images/tech-pen-180.webp" |
  "/images/tech-pen-200.webp" |
  "/images/tech-pen-300.webp" |
  "/images/tech-pen-32.webp" |
  "/images/tech-pen-400.webp" |
  "/images/tech-pen-64.webp" |
  "/images/tech-pen-96.webp";
export const $aicon = (icon: AIcon) => icon;
