import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

for (const name of ["pow5-217a", "pow5-64b"]) {
  const sourcePath = join(__dirname, "src", `${name}.wgsl`);
  const outputPath = join(__dirname, "src", `${name}-wgsl-code.ts`);
  const source = readFileSync(sourcePath, "utf8");

  writeFileSync(
    outputPath,
    [
      "// Generated by build-wgsl-modules.ts. Do not edit directly.",
      `const wgslCode = ${JSON.stringify(source)};`,
      "",
      "export default wgslCode;",
      "",
    ].join("\n"),
  );
}
